services:
  backend:
    build:
      context: ../
      dockerfile: deployment/backend/Dockerfile
    container_name: battleships-backend
    ports:
      - '3001:3001'
    command: node ./dist/backend/src/main.js
  frontend:
    build:
      context: ../
      dockerfile: deployment/frontend/Dockerfile
    container_name: battleships-frontend
    ports:
      - '5173:5173'
    command: npm run dev
