name: battleships-backend
services:
  - name: backend
    http_port: 3001
    image:
      registry_type: GHCR
      registry: jaunerc
      repository: battleships/backend
      tag: ${IMAGE_TAG}
      registry_credentials: "jaunerc:${GHCR_READ_PACKAGE_TOKEN}"
