name: battleships-backend
services:
  - name: backend
    image:
      registry_type: GHCR
      registry: jaunerc
      repository: battleships
      tag: ${IMAGE_TAG}
      registry_credentials: "jaunerc:${GHCR_READ_PACKAGE_TOKEN}"
