name: Development

on:
  pull_request:
    types:
        - opened
        - edited
        - synchronize
        - reopened
  workflow_call:

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.2.2
      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
      - name: install dependencies
        run: |
          cd backend
          npm install
      - name: lint
        run: |
          cd backend
          npm run lint
      - name: build
        run: |
          cd backend
          npm run build
      - name: unit tests
        run: |
          cd backend
          npm run test
  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.2.2
      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
      - name: install dependencies
        run: |
          cd frontend
          npm install
      - name: lint
        run: |
          cd frontend
          npm run lint
      - name: unit tests
        run: |
          cd frontend
          npm run test
