name: Main

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: battleships

jobs:
  build-and-test:
    uses: jaunerc/battleships/.github/workflows/development.yml@main
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: deploy backend to azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './backend'
