name: Main

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    uses: jaunerc/battleships/.github/workflows/development.yml@main
  build-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and push container image to registry (backend)
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/jaunerc/battleships/backend:${{ github.sha }}
          file: ./deployment/backend/Dockerfile

      - name: Build and push container image to registry (frontend)
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/jaunerc/battleships/frontend:${{ github.sha }}
          file: ./deployment/frontend/Dockerfile
  deploy:
    needs: build-docker-image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.2.2

      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action/deploy@v2
        env:
          SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
          IMAGE_TAG: ${{ github.sha }}
          GHCR_READ_PACKAGE_TOKEN: ${{ secrets.GHCR_READ_PACKAGE_TOKEN }}
        with:
          app_spec_location: '.do/app.yaml'
          token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}